# Generated by Django 5.0.7 on 2024-07-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosy_app', '0006_product_category_alter_post_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_category',
        ),
    ]
